config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  resources :items do
    resources :remarks
    member do
      get 'complete'
    end
  end

  resources :categories

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users

  get "/admin", to: "users#admin"
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  VALID_EMAIL_ADDRESS = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false }, presence: true, format: { with: VALID_EMAIL_ADDRESS, on: :create }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, if: :password

  has_many :items, dependent: :destroy
  has_many :categories, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  http_basic_authenticate_with name:"zephyr", password:"strongpasswd", only: :admin
  def admin
    @users = User.all
  end
  
  def show
    @user = current_user
  end

  def new
    if logged_in?
      redirect_to items_path
      return
    end
    @user = User.new
  end

  def create
    if logged_in?
      redirect_to items_path
      return
    end
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "You have been successfully registered!"
      redirect_to items_path
    else
      flash.now[:danger] = "The following error(s) prohibited this user from being saved:\n\r ♣ " + @user.errors.full_messages.join(" ♣ ")
      render "new", status: :bad_request
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    user = User.find(current_user.id)
    if params[:change] == "details"
      status = user.update_attributes(user_params)
    elsif params[:change] == "password" && user.authenticate(params[:user][:current_password])
      status = user.update_attributes(user_params)
    end
    if status
      flash[:success] = "Successfully updated details."
      redirect_to current_user
    else
      @user = user
      if !user.authenticate(params[:user][:current_password])
        flash.now[:danger] = "The following error(s) prohibited this user from being saved:\n\r ♣ Invalid password, authentication failed "
      else
        flash.now[:danger] = "The following error(s) prohibited this user from being saved:\n\r ♣ " + @user.errors.full_messages.join(" ♣ ")
      end
      flash.now[:danger] ||= "Error! Please try again."
      render "edit", status: :bad_request
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user == current_user
      flash[:danger] = "Action prohibited! You cannot delete yourself!"
    else
      @user.destroy
      flash[:success] = "User " + @user.name  + " and the associated tasks and categories have been permanently deleted."
    end

    redirect_to admin_path

  end

  private
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.erb
<%= render "common/footer" %>

app/views/users/_form.html.erb
<%= form_for @user, html: { id: "needs-validation", novalidate: "novalidate" } do |u| %>
  <div class="form-group">
    <span class="form-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
    <%= u.label :email %>
    <%= u.text_field :email, class: 'form-control', placeholder: 'steven_halim@nus.edu.sg', required: true %>
  </div>
  <div class="form-group">
    <span class="form-group-addon"><i class="fa fa-pencil fa-fw"></i></span>
    <%= u.label :name %>
    <%= u.text_field :name, class: 'form-control', placeholder: 'Steven Halim' %>
  </div>
  <div class="form-group">
    <span class="form-group-addon"><i class="fa fa-key fa-fw"></i></span>
    <%= u.label :password %>
    <%= u.password_field :password, class: 'form-control', placeholder: 'i_can_do_it' %>
  </div>
  <div class="form-group">
    <span class="form-group-addon"><i class="fa fa-key fa-fw"></i></span>
    <%= u.label :password_confirmation %>
    <%= u.password_field :password_confirmation, placeholder: 'i_can_do_it', class: 'form-control' %>
  </div>
  <%= u.submit "Sign up", class: 'btn btn-primary' %>
<% end %>

app/views/users/_header.html.erb
<%= render "common/header", title: "My Workaholic", link: items_path %>
<div class="toolbar">
  <%= link_to '<i class="fa fa-chevron-left" aria-hidden="true"></i> Back'.html_safe,
      defined?(show) ? items_path : 'javascript:history.back()',
      class: 'btn btn-xs',
      title: 'Back',
      data: { toggle: 'tooltip', placement: 'bottom' } %>
</div>

app/views/users/admin.html.erb
<%= render "header", show: true %>
<h3><strong>Admin Management</strong></h3>
<hr>

<table class="table table-sm table-hover table-bordered table-striped">
  <thead class="thead-light">
    <tr>
      <th scope="col"><i class="fa fa-hashtag"></i></th>
      <th scope="col"><i class="fa fa-id-card"></i></th>
      <th scope="col"><i class="fa fa-envelope"></i></th>
      <th scope="col"><i class="fa fa-tasks"></i></th>
      <th scope="col"><i class="fa fa-tags"></i></th>
      <th scope="col"><i class="fa fa-angle-double-down"></i></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
    <tr>
      <th scope="row"><%= u.id %></th>
      <td class="name">
        <%= u.name %> (<%= u.created_at.iso8601 %>)
      </td>
      <td><%= u.email %></td>
      <td class="task name">
        <ol>
        <% u.items.all.each do |t| %>
          <li><%= link_to t.title, item_path(id: t.id) %></li>
        <% end %>
        </ol>
      </td>
      <td class="category name">
        <ol>
        <% u.categories.all.each do |c| %>
          <li><%= link_to c.name, category_path(id: c.id) %></li>
        <% end %>
        </ol>
      </td>
      <td>
	  <%= link_to '<i class="fa fa-trash"></i>'.html_safe, 
             user_path(u), method: :delete,
             data: { confirm: 'Delete user ' + u.name + ' and the associated tasks and categories from database?' },
             class: 'btn btn-xs btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= render "footer" %>

app/views/users/edit.html.erb
<% if params[:change] == "password" %>

<%= render "header" %>

<h3><strong>Change Password</strong></h3>

<hr>

  <%= form_for(@user) do |u| %>
    <div class="form-group">
      <span class="form-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
      <%= label_tag :email %>
      <%= text_field_tag :email, @user.email, class: 'form-control', disabled: "disabled" %>
    </div>
    <div class="form-group">
      <span class="form-group-addon"><i class="fa fa-key fa-fw"></i></span>
      <%= u.label :current_password %>
      <%= u.password_field :current_password, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <span class="form-group-addon"><i class="fa fa-key fa-fw"></i></span>
      <%= u.label :password %>
      <%= u.password_field :password, class: 'form-control', required: true %>
    </div>
    <div class="form-group">
      <span class="form-group-addon"><i class="fa fa-key fa-fw"></i></span>
      <%= u.label :password_confirmation %>
      <%= u.password_field :password_confirmation, class: 'form-control', required: true %>
    </div>
    <%= u.submit "Update", class: 'btn btn-primary' %>
    <%= hidden_field_tag "change", "password" %>
  <% end %>

<% elsif params[:change] == "details" %>

<%= render "header" %>

<h3><strong>Update Details</strong></h3>

<hr>

  <%= form_for(@user) do |u| %>
    <div class="form-group">
      <span class="form-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
      <%= label_tag :email %>
      <%= text_field_tag :email, @user.email, class: 'form-control', disabled: "disabled" %>
    </div>
    <div class="form-group">
      <span class="form-group-addon"><i class="fa fa-pencil fa-fw"></i></span>
      <%= u.label :name %>
      <%= u.text_field :name, class: 'form-control' %>
    </div>
    <%= u.submit "Update", class: 'btn btn-primary' %>
    <%= hidden_field_tag "change", "details" %>
  <% end %>

<% end %>

app/views/users/new.html.erb
<%= render "header" %>
<h3><strong>Sign Up</strong></h3>
<hr>
<%= render "form" %>
<%= render "footer" %>

app/views/users/show.html.erb
<%= render "header", show: true %>
<h3><strong>User Profile</strong></h3>
<hr>

<div class="form-group">
  <span class="form-group-addon"><i class="fa fa-envelope-o fa-fw"></i></span>
  <%= label_tag :email %>
  <%= text_field_tag :email, @user.email, class: 'form-control', disabled: "disabled" %>
</div>
<div class="form-group">
  <span class="form-group-addon"><i class="fa fa-pencil fa-fw"></i></span>
  <%= label_tag :name %>
  <%= text_field_tag :name, @user.name, class: 'form-control', disabled: "disabled" %>
</div>
<%= link_to "Update details", edit_user_path(current_user, change: "details"), class: "btn btn-primary" %>
<%= link_to "Change password", edit_user_path(current_user, change: "password"), class: "btn btn-primary" %>

<%= render "footer" %>